export const CUSTOMER_TEXT = {
  "account": "Tài khoản",
  "personal_info": "Thông tin cá nhân",
  "my_orders": "Đơn hàng của tôi",
  "change_password": "Đổi mật khẩu",
  "logout": "Đăng xuất",
  "logging_out": "Đang đăng xuất...",
  "login": "Đăng nhập",
  "cart": "Giỏ hàng",
  "categories": "Danh mục",
  "home": "Trang chủ",
  "products": "Sản phẩm",
  "introduction": "Giới thiệu",
  "purchase_policy": "Chính sách mua hàng",
  "contact_us": "Liên hệ",
  "quick_links": "Liên kết nhanh",
  "policies": "Chính sách",
  "copyright": "Bản quyền thuộc về Nova. Bảo lưu mọi quyền.",
  "loading_banner": "Đang tải banner...",
  "loading_sections": "Đang tải sections...",
  "loading_partners": "Đang tải đối tác...",
  "partners": "Đối tác",
  "error_prefix": "Lỗi: ",
  "price_unavailable": "Giá không có sẵn",
  "search_products": "Tìm kiếm sản phẩm",
  "search_by_name": "Tìm kiếm theo tên",
  "search_by_brand": "Tìm kiếm thương hiệu",
  "all_brands": "Tất cả thương hiệu",
  "search_by_type": "Tìm kiếm loại sản phẩm",
  "all_types": "Tất cả loại sản phẩm",
  "search_by_section": "Tìm kiếm theo mục",
  "all_sections": "Tất cả mục",
  "search_by_equipment": "Tìm kiếm theo thiết bị",
  "all_equipment": "Tất cả thiết bị",
  "sort_by": "Sắp xếp theo",
  "created_date": "Ngày tạo",
  "rating": "Đánh giá",
  "purchases": "Lượt mua",
  "descending": "Giảm dần",
  "ascending": "Tăng dần",
  "search": "Tìm kiếm",
  "filters": "Bộ lọc",
  "product_filters": "Bộ lọc sản phẩm",
  "login_now": "Đăng nhập ngay",
  "loading_product_details": "Đang tải chi tiết sản phẩm...",
  "product_not_found": "Sản phẩm không tìm thấy.",
  "product_does_not_exist": "Sản phẩm không tồn tại",
  "failed_to_load_product": "Không thể tải thông tin sản phẩm",
  "failed_to_load_reviews": "Không thể tải đánh giá sản phẩm",
  "login_to_add_cart": "Vui lòng đăng nhập để thêm sản phẩm vào giỏ hàng!",
  "login_to_review": "Vui lòng đăng nhập để đánh giá sản phẩm!",
  "review_submitted": "Đánh giá sản phẩm thành công",
  "review_updated": "Đã cập nhật đánh giá",
  "review_deleted": "Đánh giá đã được xóa!",
  "failed_to_submit_review": "Không thể gửi đánh giá",
  "failed_to_delete_review": "Không thể xóa đánh giá",
  "product_description": "Mô tả sản phẩm",
  "specifications": "Thông số kỹ thuật",
  "reference_documents": "Tài liệu tham khảo",
  "other_documents": "Tài liệu khác",
  "features": "Tính năng",
  "operating_method": "Cách hoạt động",
  "advantages": "Ưu điểm",
  "no_reviews_yet": "Chưa có đánh giá nào",
  "comment": "Bình luận",
  "processing": "Đang xử lý...",
  "update_review": "Cập nhật đánh giá",
  "submit_review": "Gửi đánh giá",
  "delete_review": "Xóa đánh giá",
  "customer_support": "Chăm sóc khách hàng",
  "hotline": "Đường dây nóng",
  "send_email": "Gửi Email",
  "faqs": "Vấn đề thường gặp",
  "return_warranty": "Đổi trả & Bảo hành",
  "genuine_100": "100% Chính hãng",
  "genuine_warranty_label": "Tem bảo hành chính hãng",
  "return_3_days": "3 ngày đổi trả",
  "out_of_stock": "Trạng thái: Liên hệ",
  "quantity_left": "Số lượng đang còn: ",
  "add_to_cart": "Thêm vào giỏ hàng",
  "quantity": "Số lượng",
  "image": "Hình ảnh",
  "product_name": "Tên sản phẩm",
  "cart_empty": "Giỏ hàng của bạn hiện tại trống.",
  "login_to_order": "Bạn cần phải đăng nhập để đặt hàng",
  "no_items_selected": "Bạn chưa chọn sản phẩm nào để đặt hàng!",
  "insufficient_stock": "Không đủ hàng cho sản phẩm {name}, chỉ còn {qty} sản phẩm.",
  "order_success": "Đặt hàng thành công",
  "clear_cart": "Xóa giỏ hàng",
  "place_order": "Đặt hàng",
  "confirm_clear_cart": "Xác nhận xóa giỏ hàng",
  "confirm_clear_cart_msg": "Bạn có chắc chắn muốn xóa toàn bộ giỏ hàng không?",
  "cancel": "Hủy",
  "clear": "Xóa",
  "price": "Giá",
  "attributes": "Thuộc tính",
  "no_product_info": "Không tìm thấy thông tin sản phẩm.",
  "product_unavailable": "Sản phẩm hiện không khả dụng.",
  "remove_unavailable_product": "Hãy xóa sản phẩm này khỏi giỏ hàng.",
  "contact_only_product": "Sản phẩm này hiện chỉ nhận liên hệ.",
  "min_qty_warning": "Số lượng tối thiểu là 1!",
  "max_qty_warning": "Số lượng tối đa là ",
  "insufficient_stock_general": "Không còn đủ số lượng hàng để đặt thêm",
  "total": "Tổng:",
  "orders_list": "Danh sách đơn hàng",
  "login_to_view_orders": "Bạn chưa đăng nhập! Vui lòng đăng nhập để xem đơn hàng.",
  "session_expired": "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại!",
  "error_loading_orders": "Lỗi khi tải đơn hàng: ",
  "cancel_order_failed": "Hủy đơn hàng thất bại!",
  "cancel_order_success": "Hủy đơn hàng thành công!",
  "cancelled": "Đã hủy",
  "state_processing": "Đang xử lý",
  "delivering": "Đang giao hàng",
  "completed": "Hoàn thành",
  "no_processing_orders": "Không có đơn hàng nào đang xử lý.",
  "no_delivering_orders": "Không có đơn hàng nào đang được giao.",
  "no_completed_orders": "Không có đơn hàng nào đã hoàn thành.",
  "no_cancelled_orders": "Không có đơn hàng nào bị hủy.",
  "no_orders_yet": "Bạn chưa có đơn hàng nào.",
  "all": "Tất cả",
  "login_to_view_orders_table": "Đăng nhập để xem danh sách đơn hàng.",
  "order_code": "Mã đơn",
  "order_date": "Ngày đặt",
  "total_money": "Tổng tiền",
  "payment": "Thanh toán",
  "status": "Trạng thái",
  "paid": "Đã thanh toán",
  "unpaid": "Chưa thanh toán",
  "order_details": "Chi tiết đơn hàng",
  "order_code_label": "Mã đơn hàng:",
  "product_list": "Danh sách sản phẩm:",
  "cancel_order": "Hủy đơn hàng",
  "close": "Đóng",
  "confirm_cancel_order": "Xác nhận hủy đơn hàng",
  "confirm_cancel_order_msg": "Bạn có chắc chắn muốn hủy đơn hàng {id} không?",
  "no": "Không",
  "yes": "Có",
  "full_name": "Họ và tên",
  "phone_number": "Số điện thoại",
  "email_address": "Địa chỉ email",
  "address": "Địa chỉ",
  "save_changes": "Lưu thay đổi",
  "current_password": "Mật khẩu hiện tại",
  "new_password": "Mật khẩu mới",
  "confirm_new_password": "Xác nhận mật khẩu mới",
  "passwords_do_not_match": "Mật khẩu mới không trùng khớp!",
  "CẢM BIẾN": "CẢM BIẾN",
  "ĐỘNG CƠ HỘP SỐ": "ĐỘNG CƠ HỘP SỐ",
  "THIẾT BỊ ĐIỆN": "THIẾT BỊ ĐIỆN",
  "XILANH KHÍ NÉN": "XILANH KHÍ NÉN",
  "HỆ THỐNG CÂN LỌC BỤI": "HỆ THỐNG CÂN LỌC BỤI",
  "PHỤ KIỆN TRẠM TRỘN": "PHỤ KIỆN TRẠM TRỘN",
  "VẬT LIỆU": "VẬT LIỆU",
  "CÁNH TAY BỘ TRỘN": "CÁNH TAY BỘ TRỘN",
  "PHỤ KIỆN BÊ TÔNG": "PHỤ KIỆN BÊ TÔNG",
  "TỦ ĐIỆN ĐIỀU KHIỂN": "TỦ ĐIỆN ĐIỀU KHIỂN",
  "CỤM TRUNG TÂM": "CỤM TRUNG TÂM",
  "CỤM BĂNG": "CỤM BĂNG",
  "CỤM CỐI": "CỤM CỐI",
  "CỤM CỐT LIỆU": "CỤM CỐT LIỆU",
  "CỤM SILO": "CỤM SILO",
  "TRẠM TRỘN BÊ TÔNG": "TRẠM TRỘN BÊ TÔNG",
  "already_have_account_login": "Đã có tài khoản? Đăng nhập ngay",
  "dont_have_account_register": "Chưa có tài khoản? Đăng ký ngay",
  "location": "Vị trí",
  "product_count": "Số sản phẩm",
  "details": "Chi tiết",
  "footer_brand_desc": "Nova - Website bán hàng thiết bị công nghiệp, tự động hóa và linh kiện kỹ thuật.",
  "footer_address": "Số 25 ngõ 77, Bùi Xương Trạch, Khương Đình, Thanh Xuân, Hà Nội",
  "connect_with_us": "Kết nối với chúng tôi",
  "failed_to_load_profile": "Không thể tải thông tin hồ sơ",
  "update_failed": "Cập nhật thất bại",
  "update_success": "Cập nhật thông tin thành công!",
  "fill_all_address_fields": "Vui lòng điền đầy đủ các thông tin địa chỉ!",
  "failed_to_save_address": "Không thể lưu địa chỉ",
  "update_address_success": "Cập nhật địa chỉ thành công!",
  "add_address_success": "Thêm địa chỉ thành công!",
  "confirm_delete_address": "Bạn có chắc chắn muốn xóa địa chỉ này?",
  "failed_to_delete_address": "Không thể xóa địa chỉ",
  "delete_address_success": "Xóa địa chỉ thành công!",
  "failed_to_set_default_address": "Không thể thiết lập địa chỉ mặc định",
  "set_default_address_success": "Đã đặt làm địa chỉ mặc định!",
  "account_info": "Thông tin tài khoản",
  "phone_number_used_for_login": "Số điện thoại dùng làm thông tin tài khoản đăng nhập",
  "not_updated_yet": "Chưa cập nhật",
  "address_book": "Địa chỉ của tôi",
  "add_address": "Thêm địa chỉ",
  "no_addresses_saved": "Bạn chưa lưu địa chỉ giao hàng nào. Địa chỉ được thêm hoặc sử dụng khi đặt hàng sẽ hiển thị tại đây.",
  "receiver": "Người nhận",
  "edit_construction_address": "Chỉnh sửa địa chỉ giao hàng",
  "add_construction_address": "Thêm địa chỉ giao hàng mới",
  "address_label_placeholder": "Tên gợi nhớ (Ví dụ: Nhà riêng, Văn phòng)",
  "receiver_name": "Tên người nhận",
  "receiver_phone": "Số điện thoại người nhận",
  "address_detail_label": "Địa chỉ giao hàng chi tiết",
  "address_detail_placeholder": "Số nhà, tên đường, phường/xã, tỉnh/thành phố",
  "province_city": "Tỉnh/Thành phố",
  "ward_commune": "Xã/Phường/Đặc khu",
  "select_province_city": "Chọn Tỉnh/Thành phố",
  "select_ward_commune": "Chọn Xã/Phường/Đặc khu",
  "select_province_first": "Chọn Tỉnh/Thành phố trước",
  "address_line": "Địa chỉ cụ thể",
  "address_line_placeholder": "Số nhà, tên đường, tòa nhà...",
  "address_form_hint": "Nhập thông tin người nhận và địa chỉ giao hàng.",
  "address_type": "Loại địa chỉ",
  "home_address": "Nhà riêng",
  "office_address": "Văn phòng",
  "set_as_default_address": "Đặt làm địa chỉ mặc định",
  "complete": "Hoàn thành",
  "save_address": "Lưu địa chỉ",
  "passwords_do_not_match_signup": "Mật khẩu không khớp",
  "phone_validation_msg": "Số điện thoại phải có đúng 10 chữ số",
  "email_required_msg": "Vui lòng nhập email",
  "email_validation_msg": "Email không đúng định dạng",
  "register_success": "Đăng ký thành công",
  "login_identifier_required": "Vui lòng nhập số điện thoại hoặc email",
  "login_identifier_invalid": "Vui lòng nhập đúng số điện thoại (10 số) hoặc địa chỉ email",
  "login_success": "Đăng nhập thành công",
  "invalid_credentials": "Số điện thoại/Email hoặc mật khẩu không đúng",
  "forgot_identifier_required": "Vui lòng nhập số điện thoại hoặc email",
  "otp_sent_success": "Mã OTP đã được gửi",
  "otp_invalid": "Vui lòng nhập mã OTP gồm 6 chữ số",
  "reset_password_success": "Đặt lại mật khẩu thành công",
  "create_account": "Tạo tài khoản",
  "out_of_stock_val": "Liên hệ",
  "quantity_left_val": "Còn lại: ",
  "contact_phone": "Liên hệ: 0901 513 825",
  "add_to_cart_short": "Thêm vào giỏ",
  "password": "Mật khẩu",
  "confirm_password": "Xác nhận mật khẩu",
  "register": "Đăng ký",
  "forgot_password_title": "Quên mật khẩu",
  "forgot_password_desc": "Nhập số điện thoại hoặc email của bạn để nhận mã OTP khôi phục mật khẩu.",
  "phone_or_email": "Số điện thoại hoặc Email",
  "otp_email_note": "Lưu ý: Mã OTP sẽ gửi về email đăng ký của khách hàng. OTP có hiệu lực trong vòng 5 phút!",
  "send_otp": "Gửi mã OTP",
  "back_to_login": "Quay lại đăng nhập",
  "reset_password_title": "Đặt lại mật khẩu",
  "otp_sent_to": "Mã OTP đã được gửi đến email liên kết của tài khoản:",
  "otp_placeholder": "Nhập mã OTP 6 số",
  "confirm_reset": "Xác nhận",
  "back": "Quay lại",
  "forgot_password": "Quên mật khẩu?",
  "welcome": "Chào mừng!",
  "fill_to_register": "Hãy điền thông tin để tạo tài khoản",
  "hello": "Xin chào!",
  "login_to_use_all_features": "Hãy đăng nhập để sử dụng hết các tính năng",
  "open_categories": "Mở danh mục",
  "search_placeholder": "Tìm sản phẩm, mã sản phẩm, hãng...",
  "customer_utilities": "Tiện ích khách hàng",
  "account_fallback": "Tài khoản",
  "logout_success": "Đăng xuất thành công",
  "logout_failed": "Đăng xuất thất bại",
  "generic_error_retry": "Đã xảy ra lỗi. Vui lòng thử lại sau.",
  "mobile_navigation": "Điều hướng trên điện thoại",
  "support": "Hỗ trợ",
  "back_to_top": "Lên đầu trang",
  "shipping_policy": "Vận chuyển & giao nhận",
  "privacy_policy": "Chính sách bảo mật",
  "shopping_guide": "Hướng dẫn mua hàng",
  "warranty_request": "Yêu cầu bảo hành",
  "send_support_request": "Gửi yêu cầu hỗ trợ",
  "technical_support_247": "Hỗ trợ kỹ thuật 24/7",
  "hotline_label": "Hotline",
  "breadcrumb": "Đường dẫn điều hướng",
  "brand_label": "Hãng:",
  "token_expired_login": "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
  "login_required_action": "Bạn cần đăng nhập để thực hiện hành động này.",
  "add_cart_success": "Đã thêm sản phẩm vào giỏ hàng.",
  "cart_status_updated": "Đã cập nhật trạng thái sản phẩm.",
  "cart_cleared": "Đã xóa toàn bộ giỏ hàng.",
  "view_all": "Xem tất cả",
  "view_all_categories": "Xem tất cả danh mục",
  "industrial_solutions": "NOVA INDUSTRIAL SOLUTIONS",
  "equipment_solutions": "Giải pháp thiết bị",
  "for_industrial_equipment_systems": "cho hệ thống thiết bị công nghiệp",
  "genuine_quality": "Chính hãng - Chất lượng",
  "expert_technical_consulting": "Tư vấn kỹ thuật chuyên sâu",
  "official_warranty": "Bảo hành chính hãng",
  "explore_now": "Khám phá ngay",
  "download_catalogue": "Tải catalogue",
  "featured_categories": "Danh mục nổi bật",
  "loading_products": "Đang tải sản phẩm...",
  "add_to_favorites": "Thêm vào yêu thích",
  "featured_brands": "Thương hiệu nổi bật",
  "view_more": "Xem thêm",
  "product_type_label": "Loại sản phẩm:",
  "cluster_label": "Cụm:",
  "equipment_label": "Thiết bị:",
  "real_image_100": "Ảnh thật 100%",
  "return_by_policy": "Đổi trả theo chính sách",
  "reviews_suffix": "đánh giá",
  "sold_label": "Đã bán",
  "vat_excluded": "Giá chưa bao gồm VAT",
  "buy_now": "Mua ngay",
  "call_now": "Gọi ngay 0901.51.38.25",
  "hotline_number": "Đường dây nóng 0901.51.38.25",
  "NOVA_commitment": "Cam kết từ NOVA",
  "nationwide_delivery": "Giao hàng toàn quốc",
  "related_products": "Sản phẩm liên quan",
  "product_info_updating": "Thông tin sản phẩm đang được cập nhật.",
  "manual_label": "Hướng dẫn sử dụng",
  "datasheet_label": "Bảng thông số",
  "catalog_label": "Catalogue",
  "chat": "Chat",
  "call": "Gọi",
  "contact_for_quote": "Liên hệ báo giá",
  "customer_information": "Thông tin dành cho khách hàng",
  "policy_page_description": "Tìm hiểu quy định mua hàng, giao nhận, bảo hành và bảo mật thông tin tại NOVA.",
  "loading_policy_content": "Đang tải nội dung chính sách...",
  "policy_categories": "Danh mục chính sách",
  "need_help": "Cần hỗ trợ?",
  "support_team_ready": "Đội ngũ NOVA sẵn sàng giải đáp.",
  "last_updated": "Cập nhật lần cuối:",
  "policy_contact_prompt": "Nếu còn câu hỏi về chính sách này, vui lòng liên hệ để được hỗ trợ.",
  "contact_now": "Liên hệ ngay",
  "policy_load_error": "Không thể tải nội dung chính sách. Vui lòng thử lại sau.",
  "login_required_title": "Yêu cầu đăng nhập",
  "list_view": "Danh sách",
  "grid_view": "Lưới",
  "actions": "Thao tác",
  "active": "Hoạt động",
  "code_label": "Mã:",
  "showing": "Hiển thị",
  "of": "trong số",
  "devices_unit": "thiết bị",
  "per_page": "/ trang",
  "item_label": "Viên",
  "button_count": "Số nút",
  "rows_per_page_10": "10 hàng mỗi trang",
  "view_details": "Xem chi tiết",
  "image_heading": "Hình ảnh",
  "display_range": "Hiển thị",
  "page_size_10": "10 / trang",
  "page_size_20": "20 / trang",
  "page_size_50": "50 / trang",
  "policy_purchase_title": "Chính sách mua hàng",
  "policy_warranty_title": "Bảo hành & đổi trả",
  "policy_shipping_title": "Vận chuyển & giao nhận",
  "policy_privacy_title": "Chính sách bảo mật",
  "policy_purchase_short": "Mua hàng",
  "policy_warranty_short": "Bảo hành & đổi trả",
  "policy_shipping_short": "Vận chuyển",
  "policy_privacy_short": "Bảo mật",
  "unknown": "Chưa rõ",
  "stock_quantity": "Số lượng tồn",
  "add_product_to_cart": "Thêm sản phẩm vào giỏ hàng",
  "search_result_prefix": "Tìm kiếm",
  "product_display_range": "Hiển thị {first}–{last} trong {total} sản phẩm",
  "product_code_label": "Mã sản phẩm",
  "manufacturer_label": "Hãng sản xuất",
  "product_type_summary_label": "Loại sản phẩm",
  "color_label": "Màu sắc",
  "shape_label": "Hình dạng",
  "frame_label": "Khung",
  "in_stock": "Còn hàng",
  "remaining_products": "Còn {count} sản phẩm",
  "pdf_document": "Tài liệu PDF",
  "technical_document": "Tài liệu kỹ thuật",
  "remove_from_cart": "Xóa khỏi giỏ hàng",
  "product_categories": "Danh mục sản phẩm",
  "best_selling_products": "Sản phẩm bán chạy",
  "genuine_products": "Hàng chính hãng",
  "genuine_commitment": "Cam kết 100% chính hãng",
  "trusted_warranty": "Bảo hành uy tín",
  "fast_on_time_delivery": "Giao nhanh - Đúng hẹn",
  "support_247": "Hỗ trợ 24/7",
  "free_technical_consulting": "Tư vấn kỹ thuật miễn phí",
  "category": "Danh mục",
  "unknown_error": "Đã xảy ra lỗi không xác định.",
  "device_display_range": "Hiển thị {first}–{last} trong số {total} thiết bị",
  "updating_status": "Đang cập nhật",
  "introduction_empty": "Chưa có nội dung giới thiệu.",
  "loading_introduction": "Đang tải nội dung giới thiệu...",
  "introduction_load_error": "Không thể tải nội dung giới thiệu. Vui lòng thử lại sau.",
  "error_occurred": "Đã xảy ra lỗi",
  "password_strength_weak": "Yếu",
  "password_strength_medium": "Trung bình",
  "password_strength_good": "Tốt",
  "password_strength_strong": "Mạnh",
  "fill_all_fields": "Vui lòng nhập đầy đủ thông tin",
  "password_minimum_length": "Mật khẩu phải có ít nhất 6 ký tự",
  "change_password_failed": "Đổi mật khẩu thất bại",
  "change_password_success": "Đổi mật khẩu thành công",
  "server_error": "Lỗi máy chủ, vui lòng thử lại sau",
  "change_password_description": "Vui lòng tạo mật khẩu mới để bảo vệ tài khoản của bạn.",
  "current_password_placeholder": "Nhập mật khẩu hiện tại",
  "toggle_password_visibility": "Hiện hoặc ẩn mật khẩu",
  "new_password_placeholder": "Nhập mật khẩu mới",
  "password_strength": "Độ mạnh mật khẩu",
  "password_rule_note": "Mật khẩu phải có ít nhất 6 ký tự; nên kết hợp chữ hoa, chữ thường, số và ký tự đặc biệt.",
  "confirm_password_placeholder": "Nhập lại mật khẩu mới",
  "encrypted_security_note": "Thông tin của bạn được mã hóa và bảo mật.",
  "copied": "Đã sao chép mã đơn",
  "copy_failed": "Không thể sao chép mã đơn",
  "other_products": "sản phẩm khác",
  "orders_description": "Theo dõi trạng thái xử lý, giao hàng và thanh toán của các đơn đã đặt.",
  "order_status": "Trạng thái đơn hàng",
  "loading_orders": "Đang tải đơn hàng...",
  "unable_to_load_orders": "Không thể tải đơn hàng",
  "try_again": "Thử lại",
  "empty_orders_hint": "Không có đơn hàng phù hợp với trạng thái bạn đang chọn.",
  "continue_shopping": "Tiếp tục mua sắm",
  "copy_order_code": "Sao chép mã đơn",
  "construction": "Công trình",
  "full_name_required": "Vui lòng nhập họ và tên",
  "account_info_description": "Quản lý thông tin liên hệ và các địa chỉ nhận hàng của bạn.",
  "personal_info_hint": "Thông tin dùng để liên hệ và xác nhận đơn hàng",
  "edit": "Chỉnh sửa",
  "account_security": "Bảo mật tài khoản",
  "change_password_regularly": "Đổi mật khẩu định kỳ để bảo vệ tài khoản của bạn.",
  "address_book_hint": "Lưu địa chỉ để đặt hàng nhanh hơn",
  "no_saved_address_title": "Chưa có địa chỉ nhận hàng nào",
  "add_new_address": "Thêm địa chỉ mới",
  "set_default": "Đặt làm mặc định",
  "default": "Mặc định",
  "delete": "Xóa",
  "my_addresses": "Địa chỉ của tôi",
  "my_account": "Tài khoản của tôi",
  "customer_support_247": "Hỗ trợ khách hàng 24/7",
  "contact_price": "Liên hệ",
  "product_image_alt": "Ảnh sản phẩm",
  "product_no_longer_exists": "Sản phẩm không còn tồn tại",
  "register_failed": "Không thể đăng ký tài khoản. Email hoặc số điện thoại có thể đã được sử dụng.",
  "otp_send_failed": "Không thể gửi mã OTP. Vui lòng kiểm tra thông tin và thử lại.",
  "reset_password_failed": "Không thể đặt lại mật khẩu. Mã OTP có thể không đúng hoặc đã hết hạn.",
  "order_creation_failed": "Không thể tạo đơn hàng. Vui lòng kiểm tra lại giỏ hàng và thử lại."
};

export const text = (key, fallback = null) => CUSTOMER_TEXT[key] ?? (fallback !== null ? fallback : key);
export const VIETNAMESE_LOCALE = "vi-VN";
